CREATE TABLE "products" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"name" varchar(256) NOT NULL,
	"classification" varchar(256),
	"quantity" integer NOT NULL,
	"available" boolean DEFAULT true NOT NULL,
	"supplier" varchar(256),
	"coordinates" jsonb,
	"price" integer NOT NULL,
	"description" text,
	"date_added" timestamp with time zone DEFAULT now() NOT NULL,
	"discount" integer DEFAULT 0 NOT NULL,
	"image" text,
	"expiration_date" timestamp with time zone,
	"weight" varchar(256),
	"brand" varchar(256),
	"category" varchar(256),
	"barcode" varchar(256),
	"unit" varchar(256),
	"min_stock_level" integer,
	"max_stock_level" integer,
	"cost_price" integer,
	"profit_margin" integer,
	CONSTRAINT "products_barcode_unique" UNIQUE("barcode")
);
